### ISSUE TITLE
Saving settings results in 2 notifications.

### ISSUE THREAD

**Issue by mrtwebdesign** [kissplugins/KISS-maintenance-mode#12]
This message is doubled:
**Settings saved. If you have enabled Maintenance Mode below, please open an Incognito or Private Web Browser window to review your Splash page. You may need to clear both your server and/or browser caches several times to see it.**
![Screenshot 2024-12-09 at 11 43 08 AM](https://github.com/user-attachments/assets/5c853ea9-aadc-4666-bd00-b64aa973d7a1)

**Comment by noelsaw1** [comment]
@mrtwebdesign there was already an issue #1 from yesterday for this.
